version: '3.8'

services:
    tweedledo-backend:
      container_name: tweedledo-backend
      environment:
       - POSTGRES_URL=host=postgres user=postgres password=postgres dbname=localdb port=5432 sslmode=disable
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
       postgres:
         condition: service_healthy
      ports:
        - "8080:8080"

    postgres:
        image: postgres:latest
        restart: always
        container_name: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=localdb
        ports:
          - '5432:5432'
        volumes: 
          - ./infrastructure/db/data:/var/lib/postgresql/data
          - ./infrastructure/db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
          test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d localdb'" ]
          interval: 10s
          timeout: 5s
          retries: 3